### PR TITLE
Add TypedFragment to TR

### PR DESCRIPTION
**Pull request by erawhctim**
Added a new `TypedFragment` trait to `TR.scala` following the existing convention for `TypedActivity`, so the TR features can be used with fragments.

### CODE REVIEW

**Comment by pfn** [comment]
This is handy, however, I'd like to somehow see support fragments also be supported. This can potentially be handled by inspecting the classpath/libraryDependencies for the presence of support-v4

**Comment by erawhctim** [comment]
Could you not just add duplicate entries for both Fragment types and use their fully-qualified types explicitly?

**Comment by erawhctim** [comment]
One a separate note, I could use this functionality right now, but I am unsure how to build my fork of this plugin locally to see these changes. How do I do that?

**Comment by pfn** [comment]
`sbt publish-local` (make sure to update the version in build.sbt first)

**Comment by pfn** [comment]
As for including both variants. It will cause a build failure if you include a support fragment import while not using the support fragment library.

**Comment by pfn** [comment]
I'm going to reject this and the possibility of adding this extension. Mostly because: you can do getActivity.findView(TR.foo).

The alternative is a bunch of build-time logic to detect platformTarget is at least android-11 or the presence of the support-v4 library.

**Comment by pfn** [comment]
Also, the view may not be attached to the activity yet, and it is fraught with peril to do this. (Particularly in onCreateView)

**Pull request closed without merging**
