### PR TITLE
Add explicit LD_LIBRARY_PATH to renderscript llvm command.

### PR DESCRIPTION
**Pull request by zbsz**
This solves a problem described here: https://code.google.com/p/android/issues/detail?id=58406.

### CODE REVIEW

**Comment by pfn** [comment]
I'm confused, why does setting `LD_LIBRARY_PATH` to `.` work? The build-tools directory shouldn't be the cwd, so it should continue to fail...

**Comment by zbsz** [comment]
Second parameter is the working directory for command, so actually in that case cwd is set to build-tools dir. Alternatively we can set something else (like base project dir) and use full path as LD_LIBRARY_PATH, but this solution works fine for me, so I left it like that.

**Comment by aij** [comment]
I haven't looked at the details of the commands being run, but I just wanted to point out that in general, adding "." to LD_LIBRARY_PATH is a terrible plan. It's really easy to end up with a vulnerability where you end up executing code from a directory you didn't intend to.

**Comment by pfn** [comment]
I agree, it shouldn't be .; please update the PR to properly detect the
correct build-tools path and set it explicitly.

Unfortunately, I don't have a key for BuildTools, so you have to derive
build tools path from buildToolsVersion and sdkManager

something like:

val bt = buildToolsVersion.value map { version =>
  sdkManager.value.getBuildTool(FullRevision.parseRevision(version))
} getOrElse {
  val tools = sdkManager.value.getLatestBuildTool
  tools
}

bt.getLocation

**Comment by zbsz** [comment]
Fixed.
In that case using "." was safe, working dir was explicitly set (second parameter to Process()).
But I agree that it's clearer to just pass proper path in there. And it's easy to get the path from rs executable path.

**Pull request merged**
